### ISSUE TITLE
I am interested in using sqlite in browser, could you give some info about this library? thanks

### ISSUE THREAD

**Issue by YagoLopez** [ornorm/libsqlite#1]

**Comment by ornorm** [comment]
Hi, nice To see that someone is interested by the lib.
Ok this port of the es5 version. This work is not documented because I haven't enougth sparetime. But I can test and debug the lib for you week à write the readme.md

**Comment by YagoLopez** [comment]
Dont want to bother. If you get time to write some doc in the future let me know it in this thread please. I understand. I hate code documentation 😄

**Comment by ornorm** [comment]
I make the doc this week it's sure. I can say you that i wrote this lib has complete port of the native android sqlite package. It work in the way.

**Comment by YagoLopez** [comment]
Great. That's exactly what i am looking for. I tried several sqlite packages on npm to create a database in the browser but you need to compile it with python or something like that and couldnt make it work with webpack. It would be nice to have some indications to try your lib. When you have some news please let me know.
